### ISSUE TITLE
Convert IRC style nick mentions to @-style

### ISSUE THREAD

**Issue by mkaito** [gitterHQ/irc-bridge#35] opened 2015-10-16 15:56 UTC
Tab completion found in most IRC clients usually take the form of `nick: <message>`. This does not highlight the user in gitter, though. Prefixing with an `@` usually negates tab completion, making the workflow quite tiresome (tab complete a nick, delete colon, jump to start, add `@`).

**Comment by MadLittleMods** [comment] 2015-10-17 01:58
Duplicate of https://github.com/gitterHQ/irc-bridge/issues/2 which points to https://github.com/gitterHQ/gitter/issues/158

**Closed by MadLittleMods** 2015-10-17 01:58 UTC
