### ISSUE TITLE
Unable to remain connected to the bridge in Hexchat

### ISSUE THREAD

**Issue by io7m** [gitterHQ/irc-bridge#103] opened 2018-03-06 12:06 UTC
Hello.

When I connect to `irc.gitter.im`, the following happens repeatedly in Hexchat:

```
* - Message of the Day -
* - Welcome To Gitter IRC!
* - Info at https://irc.gitter.im
* - Code at https://github.com/gitterHQ/irc-bridge
* End of /MOTD command.
* PONG :irc.gitter.im
* PONG :irc.gitter.im
* No ping reply for 79 seconds, disconnecting.
* Disconnected ()
```

Hexchat then reconnects and the same thing happens 79 seconds later. Amusingly, it's always exactly 79 seconds.

The _raw log_ shows the following protocol messages:

```
<< PING LAG1520287876075
>> PONG :irc.gitter.im
>> PING :irc.gitter.im
<< PONG :irc.gitter.im
<< PING LAG1520287906075
>> PONG :irc.gitter.im
>> PING :irc.gitter.im
<< PONG :irc.gitter.im
```

At this point, the client appears to disconnect.

**Comment by auscompgeek** [comment] 2018-03-06 12:09
I think this is the same underlying issue as #34.

**Comment by auscompgeek** [comment] 2018-03-06 12:10
Duplicate of #34

**Comment by io7m** [comment] 2018-03-06 12:23
Are you sure?

The comments in that ticket seem to imply that this is related to ZNC. I'm not using ZNC. It's a completely vanilla hexchat install with almost no configuration changes.

**Comment by auscompgeek** [comment] 2018-03-06 14:29
Yes, #34 is not actually related to ZNC. See https://github.com/gitterHQ/irc-bridge/issues/34#issuecomment-157908680.

**Comment by io7m** [comment] 2018-03-06 14:46
Got it.

**Closed** 2018-03-07 00:32 UTC
