### ISSUE TITLE
Gitter uploads are shown wrong

### ISSUE THREAD

**Issue by nipos** [gitterHQ/irc-bridge#98] opened 2017-10-28 17:30 UTC
If someone uploads an image directly at Gitter,it is converted to markdown.
Instead of showing the normal link,Pidgin shows a clickable markdown code.
It doesn't detect correctly where the real link ends so I get an error when I open it in the browser and have to rewrite it manually.
It would be great,if the bridge would convert this:
`[![image.png](https://files.gitter.im/TheServerName/channel/someCode/thumb/image.png)](https://files.gitter.im/TheServerName/channel/someCode/image.png)`
into this:
`https://files.gitter.im/TheServerName/channel/someCode/image.png`

**Comment by MadLittleMods** [comment] 2017-10-30 00:38
Duplicate of https://github.com/gitterHQ/irc-bridge/issues/44

**Closed by MadLittleMods** 2017-10-30 00:38 UTC
