### ISSUE TITLE
Image Link's are completely mindblowing

### ISSUE THREAD

**Issue by InAnimaTe** [gitterHQ/irc-bridge#78] opened 2016-10-25 19:00 UTC
They come through to IRC as fully markdown defined:

```
[![preview-3.jpg](https://files.gitter.im/Team/Blah/o1NT/thumb/preview-3.jpg)](https://files.gitter.im/Team/Blah/o1NT/preview-3.jpg)
```

Because of the first link "never ending", IRC clients can't properly make it easily clickable ;(

**Comment by MadLittleMods** [comment] 2017-10-30 00:38
Duplicate of https://github.com/gitterHQ/irc-bridge/issues/44

**Closed by MadLittleMods** 2017-10-30 00:38 UTC
