### ISSUE TITLE
Disconnecting every ~20 minutes

### ISSUE THREAD

**Issue by manavortex** [gitterHQ/irc-bridge#99] opened 2017-12-19 11:43 UTC
Basically, this started a few days ago (first occurance:)

```
......
 276311  2016-12-03 18:31:36	manavortex	[16:46:34] hey :)
 276312: 2016-12-03 18:31:36	***	Playback Complete.
 .....
 276819  2016-12-03 18:50:21	manavortex	[16:46:34] hey :)
 276820: 2016-12-03 18:50:21	***	Playback Complete.
 .....
 277327  2016-12-03 18:57:05	manavortex	[16:46:34] hey :)
 277328: 2016-12-03 18:57:05	***	Playback Complete.
 .....
 277835  2016-12-03 19:15:21	manavortex	[16:46:34] hey :)
 277836: 2016-12-03 19:15:21	***	Playback Complete.
 .....
 278343  2016-12-03 19:41:18	manavortex	[16:46:34] hey :)
 278344: 2016-12-03 19:41:18	***	Playback Complete.
 .....
 278851  2016-12-03 19:52:15	manavortex	[16:46:34] hey :)
 278852: 2016-12-03 19:52:15	***	Playback Complete.
 .....
 279359  2016-12-03 20:04:06	manavortex	[16:46:34] hey :)
 279360: 2016-12-03 20:04:06	***	Playback Complete.
 .....
 279867  2016-12-03 20:09:28	manavortex	[16:46:34] hey :)
 279868: 2016-12-03 20:09:28	***	Playback Complete.
 .....
 280375  2016-12-03 20:17:35	manavortex	[16:46:34] hey :)
 280376: 2016-12-03 20:17:35	***	Playback Complete.
 
```

I'm connecting to the bridge via znc, which is the one losing the connection. The error I get is this:

```
=!= | irc: reading data on socket: error -54 Error in the pull function.
```

Is there any intel you can get me?
Thanks for maintaining this!

**Comment by MadLittleMods** [comment] 2017-12-19 14:00
@manavortex  Perhaps a duplicate of https://github.com/gitterHQ/irc-bridge/issues/94

**Comment by OlegYch** [comment] 2018-01-03 02:21
@MadLittleMods any idea why #96 was never merged (and #94 never fixed) ?

**Comment by MadLittleMods** [comment] 2018-01-04 03:31
@OlegYch No review bandwidth.

https://github.com/gitterHQ/irc-bridge/pull/96 is now merged and deployed :tada:

**Closed by MadLittleMods** 2018-01-04 03:31 UTC

**Comment by OlegYch** [comment] 2018-01-06 18:22
thanks. working fine now
